/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Fernando GJ
 */
public class OpenFile extends javax.swing.JDialog {
    private File imgFile;
    private BufferedImage imgSelected;

    /** Creates new form OpenFile */
    public OpenFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseFile = new javax.swing.JLabel();
        openFileBtn = new javax.swing.JButton();
        startGameBtn = new javax.swing.JButton();
        previewImg = new javax.swing.JLabel();
        minImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Image for Playing");
        setResizable(false);

        chooseFile.setText("Choose File: ");

        openFileBtn.setText("OPEN IMAGE");
        openFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileBtnActionPerformed(evt);
            }
        });

        startGameBtn.setText("START GAME");
        startGameBtn.setEnabled(false);
        startGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameBtnActionPerformed(evt);
            }
        });

        minImg.setFont(new java.awt.Font("Segoe UI", 3, 8)); // NOI18N
        minImg.setText("(Min: 400x400)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minImg)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(previewImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chooseFile)
                            .addGap(34, 34, 34)
                            .addComponent(openFileBtn)
                            .addGap(44, 44, 44)
                            .addComponent(startGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFile)
                    .addComponent(openFileBtn)
                    .addComponent(startGameBtn))
                .addGap(3, 3, 3)
                .addComponent(minImg, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser(".");
        
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("JPEG (*.jpg, *jpeg)", "jpg", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("PNG (*.png)", "png"));
        
        int returnValue = fileChooser.showOpenDialog(this);
        
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                this.imgFile = fileChooser.getSelectedFile();
                this.imgSelected = ImageIO.read(imgFile);
                
                if (this.imgSelected.getWidth() >= 400 && this.imgSelected.getHeight() >= 400) {
                    Image resizedImage = new ImageIcon(imgFile.getAbsolutePath()).getImage().getScaledInstance(this.previewImg.getWidth(),
                            this.previewImg.getHeight(), Image.SCALE_SMOOTH);

                    this.previewImg.setIcon(new ImageIcon(resizedImage));
                    this.startGameBtn.setEnabled(true);
                } else
                    JOptionPane.showConfirmDialog(this, "Respect the min size", "ERROR", 
                            JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showConfirmDialog(this, "Cannot open the image", "ERROR", 
                        JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openFileBtnActionPerformed

    private void startGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameBtnActionPerformed
        this.dispose();
        
        MainWindow mainWindow = (MainWindow) this.getParent();
        mainWindow.createPuzzle(this.imgFile, new ImageIcon(this.imgFile.getAbsolutePath()).getImage(), this.imgSelected);
    }//GEN-LAST:event_startGameBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseFile;
    private javax.swing.JLabel minImg;
    private javax.swing.JButton openFileBtn;
    private javax.swing.JLabel previewImg;
    private javax.swing.JButton startGameBtn;
    // End of variables declaration//GEN-END:variables

} // end OpenFile
